# Generated by Django 3.1.5 on 2021-07-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_limitshumidityadmin_limitstemperatureadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LimitsHumidity',
            new_name='HumidityLimits',
        ),
        migrations.RenameModel(
            old_name='LimitsTemperatureAdmin',
            new_name='HumidityLimitsAdmin',
        ),
        migrations.RenameModel(
            old_name='LimitsTemperature',
            new_name='TemperatureLimits',
        ),
        migrations.RenameModel(
            old_name='LimitsHumidityAdmin',
            new_name='TemperatureLimitsAdmin',
        ),
    ]
