# Generated by Django 3.1.5 on 2021-07-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitsHumidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_humidity', models.FloatField()),
                ('max_humidity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LimtsTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date logged')),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
