# Generated by Django 3.1.5 on 2021-07-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LimtsTemperature',
            new_name='LimitsTemperature',
        ),
    ]
